### ISSUE TITLE
按住后短距离移动后再松开的bug

### ISSUE THREAD

**Issue by yilingsj** [XNAL/wxapp-movable-delete#1]
这个问题不知道怎么描述，楼主的这个案例如果是按住后【猛】的左滑或右滑是没有问题的，但是，如果用户按住后只移动一小点点距离，然后松开，此时不会自动向左滑或向右恢复原始状态。已尝试添加touchend但发现时间比bindchang要早，不知咋解。如图：https://img.alicdn.com/imgextra/i1/759415648/O1CN01X7fYEN1rapSDWRlYE_!!759415648.png

**Comment by XNAL** [comment]
bug情况写下来告知下其他人：
问题原因：按住拖动有可能触发`touchend`事件，导致`movable-view`的`bindchange`事件中的逻辑无法处理这种情况。
解决方案：添加一个`touchend`事件，单独处理这种特殊情况。
