### ISSUE TITLE
安卓的挺好，苹果手机页面左右滑动的同时，上下也可以滑动，这个很影响体验

### ISSUE THREAD

**Issue by boboweiqi93** [XNAL/wxapp-movable-delete#3]

**Comment by XNAL** [comment]
抱歉，前段时间项目很赶，加班很多，一直没来得及看这个问题。
这个问题是因为IOS上的问题，目前可以通过以下两种方式：
1、`disableScroll:true`来设置，不过页面内容过多，会导致整个页面的滚动失效，不推荐；
2、使用`scroll-view`，然后把`scroll-view`的高度设置为屏幕的高度。
